name: Docker Build Matrix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened] # trigger on PRs
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test Docker Image
    runs-on:
      group: aws-g6-12xlarge-plus
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        cuda: ['12.1.0', '12.2.0', '12.4.0', '12.6.0']
        torch: ['2.4.0', '2.5.0']
        exclude:
          # add any incompatible combinations here if needed
          - cuda: '12.99.0' # dummy value so exclude is not empty
            torch: '2.99.0'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          build-args: |
            CUDA_VERSION=${{ matrix.cuda }}
            TORCH_VERSION=${{ matrix.torch }}
          push: false
          load: true
          tags: kernels:${{ matrix.cuda }}-${{ matrix.torch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Tests
        run: |
          docker run --gpus all kernels:${{ matrix.cuda }}-${{ matrix.torch }}